services:
  backend:
    build: ./backend
    container_name: gplay-backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - default
      - coolify

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ""
    container_name: gplay-frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8002:80"
    networks:
      - default
      - coolify

networks:
  coolify:
    external: true
